In [51]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/Datasets
%ls

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/Datasets
'=1.2.0'   cwurData.csv   data.csv  'default of credit card clients (1).xlsx'

In [52]:
df=pd.read_csv('cwurData.csv')

In [53]:
df.head(3)

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012

[3 rows x 14 columns]

In [54]:
df2=df.dropna(axis=1, inplace=False)

In [55]:
df2.head(3)

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012

[3 rows x 13 columns]

In [56]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

In [57]:
find=['institution','country']
# y=df2[find]
x=df2.drop(find,inplace=False,axis=1)
y=df2['institution']

In [58]:
y.head(3)

0                       Harvard University
1    Massachusetts Institute of Technology
2                      Stanford University
Name: institution, dtype: object

In [59]:
x.head(3)

   world_rank  national_rank  quality_of_education  ...  patents   score  year
0           1              1                     7  ...        5  100.00  2012
1           2              2                     9  ...        1   91.67  2012
2           3              3                    17  ...       15   89.50  2012

[3 rows x 11 columns]

In [60]:
x_train, x_test, y_train, y_test=train_test_split(x,y,random_state=17,test_size=0.4)

In [61]:
x_train.head(3)

      world_rank  national_rank  quality_of_education  ...  patents  score  year
1124         925             13                   355  ...      737  44.36  2014
505          306             26                    70  ...      737  46.30  2014
1559         360            127                   367  ...      809  45.42  2015

[3 rows x 11 columns]

In [62]:
y_train.head()

1124    Federal University of São Carlos
505           London School of Economics
1559         College of William and Mary
1386               Iowa State University
1745            New York Medical College
Name: institution, dtype: object

In [63]:
x_test.head(3)

      world_rank  national_rank  quality_of_education  ...  patents  score  year
1236          37              2                     8  ...      871  58.80  2015
2163         964              9                   367  ...      871  44.06  2015
971          772             59                   355  ...      426  44.56  2014

[3 rows x 11 columns]

In [64]:
y_test.head(3)

1236    École normale supérieure - Paris
2163               University of Silesia
971           Saitama Medical University
Name: institution, dtype: object

In [65]:
x_train.describe()

        world_rank  national_rank  ...        score         year
count  1320.000000    1320.000000  ...  1320.000000  1320.000000
mean    459.996212      39.790152  ...    47.789015  2014.322727
std     304.194125      51.059754  ...     7.957025     0.760331
min       1.000000       1.000000  ...    43.470000  2012.000000
25%     178.750000       6.000000  ...    44.467500  2014.000000
50%     447.000000      22.000000  ...    45.110000  2014.000000
75%     726.250000      49.000000  ...    47.472500  2015.000000
max     999.000000     229.000000  ...   100.000000  2015.000000

[8 rows x 11 columns]

In [66]:
y_train.describe()

count                     1320
unique                     862
top       University of Geneva
freq                         4
Name: institution, dtype: object

In [67]:
x_test.describe()

        world_rank  national_rank  ...       score         year
count   880.000000     880.000000  ...  880.000000   880.000000
mean    458.982955      41.010227  ...   47.812466  2014.311364
std     304.681629      52.766825  ...    7.461257     0.765203
min       1.000000       1.000000  ...   43.360000  2012.000000
25%     170.750000       6.000000  ...   44.460000  2014.000000
50%     451.500000      21.000000  ...   45.080000  2014.000000
75%     723.250000      50.000000  ...   47.722500  2015.000000
max    1000.000000     228.000000  ...  100.000000  2015.000000

[8 rows x 11 columns]

In [68]:
scaler1=StandardScaler().fit(x_train)
standarized_x_train=scaler1.transform(x_train)
standarized_x_test=scaler1.transform(x_test)

In [69]:
print(standarized_x_test)

[[-1.39107397 -0.74039672 -2.20644503 ...  1.60819142  1.38433118
   0.89109796]
 [ 1.65747713 -0.60325048  0.75177892 ...  1.60819142 -0.468822
   0.89109796]
 [ 1.02606202  0.37636549  0.65289678 ... -0.03625108 -0.40596063
  -0.42461715]
 ...
 [-0.03287375 -0.09385018  0.72705838 ... -0.4094841  -0.35567153
   0.89109796]
 [ 1.3450582   0.591881    0.65289678 ... -0.47600088 -0.42230459
  -0.42461715]
 [ 0.34860622  2.57070525 -0.90449689 ... -0.23949679 -0.40218895
   0.89109796]]

In [70]:
print(standarized_x_train)

[[ 1.52922094 -0.5248812   0.65289678 ...  1.11301098 -0.43110518
  -0.42461715]
 [-0.50643508 -0.27018105 -1.69555399 ...  1.11301098 -0.18720306
  -0.42461715]
 [-0.32884958  1.7086432   0.75177892 ...  1.37907809 -0.29783907
   0.89109796]
 ...
 [-0.8320085   0.92495043 -1.41538793 ... -1.13747326 -0.00490509
  -0.42461715]
 [-0.80569954 -0.44651193 -0.68201208 ... -0.46491475 -0.08536764
   0.89109796]
 [ 1.7495585  -0.44651193  0.75177892 ...  1.24973991 -0.47259368
   0.89109796]]

In [71]:
normalizer1=Normalizer().fit(x_train)
normalized_x_train=normalizer1.transform(x_train)
normalized_x_test=normalizer1.transform(x_test)

In [72]:
print(normalized_x_train)

[[0.3303269  0.00464243 0.12677411 ... 0.26319019 0.01584141 0.71921986]
 [0.12881806 0.01094533 0.02946818 ... 0.31025788 0.0194911  0.84784176]
 [0.15027446 0.05301349 0.15319647 ... 0.33770011 0.01895963 0.84111956]
 ...
 [0.1000253  0.04203962 0.05025425 ... 0.06185139 0.02307347 0.97319297]
 [0.09989832 0.00789894 0.08967617 ... 0.14403944 0.02188935 0.93625638]
 [0.34622937 0.00593337 0.12809091 ... 0.27014268 0.01536742 0.70327841]]

In [73]:
print(normalized_x_test)

[[1.55481463e-02 8.40440340e-04 3.36176136e-03 ... 3.66011768e-01
  2.47089460e-02 8.46743642e-01]
 [3.40544799e-01 3.17936016e-03 1.29647242e-01 ... 3.07691411e-01
  1.55647343e-02 7.11823413e-01]
 [2.95104326e-01 2.25533099e-02 1.35702119e-01 ... 1.62842542e-01
  1.70334828e-02 7.69870611e-01]
 ...
 [1.88819855e-01 1.46859887e-02 1.52734282e-01 ... 1.36369895e-01
  1.88652015e-02 8.45493349e-01]
 [3.17293226e-01 2.55587179e-02 1.29619212e-01 ... 1.12093234e-01
  1.62224834e-02 7.35360826e-01]
 [2.44170850e-01 7.37689317e-02 7.16119454e-02 ... 1.60048384e-01
  1.92360039e-02 8.69265482e-01]]

In [74]:
# Practical 2.2----------------
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
bstfeatures=SelectKBest(score_func=chi2, k=10)
fit=bstfeatures.fit(x,y)
dfscr=pd.DataFrame(fit.scores_)
dfcol=pd.DataFrame(x.columns)

In [75]:
featureScores=pd.concat([dfcol,dfscr],axis=1)
featureScores.columns=['Name of Column', 'Score of Column']
print(featureScores.nlargest(100,'Score of Column'))

          Name of Column  Score of Column
0             world_rank    440963.491972
5           publications    438202.555068
6              influence    437244.326104
8                patents    362451.680690
7              citations    360984.545249
3      alumni_employment    198478.061526
1          national_rank    145811.356694
2   quality_of_education    115268.035823
4     quality_of_faculty     49271.571417
9                  score      2656.369093
10                  year         0.165038

In [76]:
featureScores

          Name of Column  Score of Column
0             world_rank    440963.491972
1          national_rank    145811.356694
2   quality_of_education    115268.035823
3      alumni_employment    198478.061526
4     quality_of_faculty     49271.571417
5           publications    438202.555068
6              influence    437244.326104
7              citations    360984.545249
8                patents    362451.680690
9                  score      2656.369093
10                  year         0.165038