In [1]:
# Name : Taukir Shekh[19DCS134]
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/Datasets
%ls

Mounted at /gdrive
/gdrive/MyDrive/Datasets
 Admission_Predict.csv
 Admission_Predict_Ver1.1.csv
'Breast Cancer Wisconsin Dataset.csv'
 cwurData.csv
 data.csv
 dataset_31_credit-g.csv
'default of credit card clients (1).xlsx'
'FIFA 19 Dataset.csv'

In [2]:
df=pd.read_csv('cwurData.csv')

In [3]:
df.head(3)

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012

[3 rows x 14 columns]

In [4]:
df2=df.dropna(axis=1, inplace=False)

In [5]:
df2.head(3)

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012

[3 rows x 13 columns]

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

In [7]:
find=['institution','country']
# y=df2[find]
x=df2.drop(find,inplace=False,axis=1)
y=df2['institution']

In [8]:
y.head(3)

0                       Harvard University
1    Massachusetts Institute of Technology
2                      Stanford University
Name: institution, dtype: object

In [9]:
x.head(3)

   world_rank  national_rank  quality_of_education  ...  patents   score  year
0           1              1                     7  ...        5  100.00  2012
1           2              2                     9  ...        1   91.67  2012
2           3              3                    17  ...       15   89.50  2012

[3 rows x 11 columns]

In [27]:
x_train, x_test, y_train, y_test=train_test_split(x,y,random_state=17,test_size=0.2)

In [28]:
x_train.head(3)

      world_rank  national_rank  quality_of_education  ...  patents  score  year
2000         801             52                   367  ...      816  44.24  2015
190           91              5                    72  ...       58  44.78  2013
1146         947             67                   355  ...      737  44.33  2014

[3 rows x 11 columns]

In [29]:
y_train.head()

2000                  University of Oldenburg
190                         Nagoya University
1146    Northwestern Polytechnical University
325                    Stony Brook University
667                    University of Konstanz
Name: institution, dtype: object

In [30]:
x_test.head(3)

      world_rank  national_rank  quality_of_education  ...  patents  score  year
1236          37              2                     8  ...      871  58.80  2015
2163         964              9                   367  ...      871  44.06  2015
971          772             59                   355  ...      426  44.56  2014

[3 rows x 11 columns]

In [31]:
y_test.head(3)

1236    École normale supérieure - Paris
2163               University of Silesia
971           Saitama Medical University
Name: institution, dtype: object

In [32]:
x_train.describe()

        world_rank  national_rank  ...        score         year
count  1760.000000    1760.000000  ...  1760.000000  1760.000000
mean    456.974432      39.726136  ...    47.854131  2014.318182
std     302.795185      51.411736  ...     7.956684     0.758435
min       1.000000       1.000000  ...    43.360000  2012.000000
25%     176.000000       6.000000  ...    44.470000  2014.000000
50%     447.000000      21.000000  ...    45.120000  2014.000000
75%     720.250000      48.000000  ...    47.560000  2015.000000
max     999.000000     229.000000  ...   100.000000  2015.000000

[8 rows x 11 columns]

In [33]:
y_train.describe()

count                                       1760
unique                                       974
top       Ludwig Maximilian University of Munich
freq                                           4
Name: institution, dtype: object

In [34]:
x_test.describe()

        world_rank  national_rank  ...       score         year
count   440.000000     440.000000  ...  440.000000   440.000000
mean    470.056818      42.486364  ...   47.575455  2014.318182
std     310.475077      53.039074  ...    6.925978     0.777612
min       1.000000       1.000000  ...   44.020000  2012.000000
25%     170.750000       6.000000  ...   44.430000  2014.000000
50%     456.000000      23.500000  ...   45.015000  2014.000000
75%     744.500000      52.000000  ...   47.520000  2015.000000
max    1000.000000     225.000000  ...  100.000000  2015.000000

[8 rows x 11 columns]

In [35]:
scaler1=StandardScaler().fit(x_train)
standarized_x_train=scaler1.transform(x_train)
standarized_x_test=scaler1.transform(x_test)

In [36]:
print(standarized_x_test)

[[-1.38738598 -0.73401254 -2.1847477  ...  1.61035419  1.37607323
   0.89923597]
 [ 1.6749595  -0.59781816  0.75522441 ...  1.61035419 -0.47698374
   0.89923597]
 [ 1.04068729  0.37499884  0.65695237 ... -0.02680875 -0.41412563
  -0.41964345]
 ...
 [ 1.52630195 -0.53944914  0.65695237 ...  1.1173658  -0.43801171
  -0.41964345]
 [ 1.14970283 -0.7145562   0.75522441 ...  0.26383366 -0.45561198
   0.89923597]
 [-1.1528374  -0.7145562  -1.26754191 ... -0.63752571  0.29114232
   0.89923597]]

In [37]:
print(standarized_x_train)

[[ 1.13648882  0.23880446  0.75522441 ...  1.40800821 -0.45435482
   0.89923597]
 [-1.20899692 -0.67564352 -1.66063011 ... -1.38068732 -0.38646807
  -1.73852288]
 [ 1.61879998  0.53064956  0.65695237 ...  1.1173658  -0.44304036
  -0.41964345]
 ...
 [-0.8257908   0.91977637 -1.39857131 ... -1.12315607 -0.01309091
  -0.41964345]
 [-0.79936279 -0.44216744 -0.66972029 ... -0.45357482 -0.09354929
   0.89923597]
 [ 1.76745752 -0.44216744  0.75522441 ...  1.25348946 -0.48075522
   0.89923597]]

In [38]:
normalizer1=Normalizer().fit(x_train)
normalized_x_train=normalizer1.transform(x_train)
normalized_x_test=normalizer1.transform(x_test)

In [39]:
print(normalized_x_train)

[[0.29837686 0.01937028 0.1367095  ... 0.30396444 0.01647964 0.75059846]
 [0.0448495  0.00246426 0.03548532 ... 0.0285854  0.0220699  0.99211046]
 [0.33788701 0.02390542 0.12666303 ... 0.26295958 0.01581682 0.71858968]
 ...
 [0.1000253  0.04203962 0.05025425 ... 0.06185139 0.02307347 0.97319297]
 [0.09989832 0.00789894 0.08967617 ... 0.14403944 0.02188935 0.93625638]
 [0.34622937 0.00593337 0.12809091 ... 0.27014268 0.01536742 0.70327841]]

In [40]:
print(normalized_x_test)

[[1.55481463e-02 8.40440340e-04 3.36176136e-03 ... 3.66011768e-01
  2.47089460e-02 8.46743642e-01]
 [3.40544799e-01 3.17936016e-03 1.29647242e-01 ... 3.07691411e-01
  1.55647343e-02 7.11823413e-01]
 [2.95104326e-01 2.25533099e-02 1.35702119e-01 ... 1.62842542e-01
  1.70334828e-02 7.69870611e-01]
 ...
 [3.18100488e-01 4.15365164e-03 1.22878861e-01 ... 2.55103438e-01
  1.53581269e-02 6.97121200e-01]
 [3.07830243e-01 1.14719345e-03 1.40339999e-01 ... 1.93110898e-01
  1.69134555e-02 7.70531603e-01]
 [5.08739592e-02 1.41316553e-03 5.65266214e-02 ... 1.22474346e-01
  2.36328383e-02 9.49176184e-01]]

In [24]:
# Practical 2.2----------------
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
bstfeatures=SelectKBest(score_func=chi2, k=10)
fit=bstfeatures.fit(x,y)
dfscr=pd.DataFrame(fit.scores_)
dfcol=pd.DataFrame(x.columns)

In [25]:
featureScores=pd.concat([dfcol,dfscr],axis=1)
featureScores.columns=['Name of Column', 'Score of Column']
print(featureScores.nlargest(100,'Score of Column'))

          Name of Column  Score of Column
0             world_rank    440963.491972
5           publications    438202.555068
6              influence    437244.326104
8                patents    362451.680690
7              citations    360984.545249
3      alumni_employment    198478.061526
1          national_rank    145811.356694
2   quality_of_education    115268.035823
4     quality_of_faculty     49271.571417
9                  score      2656.369093
10                  year         0.165038

In [26]:
featureScores

          Name of Column  Score of Column
0             world_rank    440963.491972
1          national_rank    145811.356694
2   quality_of_education    115268.035823
3      alumni_employment    198478.061526
4     quality_of_faculty     49271.571417
5           publications    438202.555068
6              influence    437244.326104
7              citations    360984.545249
8                patents    362451.680690
9                  score      2656.369093
10                  year         0.165038