In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/Datasets
%ls

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/Datasets
 Admission_Predict.csv          data.csv
 Admission_Predict_Ver1.1.csv   dataset_31_credit-g.csv
'Copy of data.csv'             'default of credit card clients.xls'
 cwurData.csv                   DS1.xlsx

In [2]:
df=pd.read_csv('cwurData.csv')

In [3]:
df.head(3)

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012

[3 rows x 14 columns]

In [4]:
df2=df.dropna(axis=1, inplace=False)

In [5]:
df2.head()

   world_rank                            institution  ...   score  year
0           1                     Harvard University  ...  100.00  2012
1           2  Massachusetts Institute of Technology  ...   91.67  2012
2           3                    Stanford University  ...   89.50  2012
3           4                University of Cambridge  ...   86.17  2012
4           5     California Institute of Technology  ...   85.21  2012

[5 rows x 13 columns]

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split

In [7]:
find=['institution','country','quality_of_education']
x=df2.drop(find,inplace=False,axis=1)
y=df2['quality_of_education']

In [8]:
y.head()

0     7
1     9
2    17
3    10
4     2
Name: quality_of_education, dtype: int64

In [9]:
x.head()

   world_rank  national_rank  alumni_employment  ...  patents   score  year
0           1              1                  9  ...        5  100.00  2012
1           2              2                 17  ...        1   91.67  2012
2           3              3                 11  ...       15   89.50  2012
3           4              1                 24  ...       50   86.17  2012
4           5              4                 29  ...       18   85.21  2012

[5 rows x 10 columns]

In [10]:
x_train, x_test, y_train, y_test=train_test_split(x,y,random_state=17,test_size=0.2)

In [11]:
x_train.head(3)

      world_rank  national_rank  alumni_employment  ...  patents  score  year
2000         801             52                567  ...      816  44.24  2015
190           91              5                101  ...       58  44.78  2013
1146         947             67                417  ...      737  44.33  2014

[3 rows x 10 columns]

In [12]:
y_train.head()

2000    367
190      72
1146    355
325     170
667     355
Name: quality_of_education, dtype: int64

In [13]:
x_test.head(3)

      world_rank  national_rank  alumni_employment  ...  patents  score  year
1236          37              2                502  ...      871  58.80  2015
2163         964              9                567  ...      871  44.06  2015
971          772             59                478  ...      426  44.56  2014

[3 rows x 10 columns]

In [14]:
y_test.head()

1236      8
2163    367
971     355
1931    367
950     355
Name: quality_of_education, dtype: int64

In [15]:
x_train.describe()

        world_rank  national_rank  ...        score         year
count  1760.000000    1760.000000  ...  1760.000000  1760.000000
mean    456.974432      39.726136  ...    47.854131  2014.318182
std     302.795185      51.411736  ...     7.956684     0.758435
min       1.000000       1.000000  ...    43.360000  2012.000000
25%     176.000000       6.000000  ...    44.470000  2014.000000
50%     447.000000      21.000000  ...    45.120000  2014.000000
75%     720.250000      48.000000  ...    47.560000  2015.000000
max     999.000000     229.000000  ...   100.000000  2015.000000

[8 rows x 10 columns]

In [16]:
y_train.describe()

count    1760.000000
mean      274.779545
std       122.144707
min         1.000000
25%       177.750000
50%       355.000000
75%       367.000000
max       367.000000
Name: quality_of_education, dtype: float64

In [17]:
x_test.describe()

        world_rank  national_rank  ...       score         year
count   440.000000     440.000000  ...  440.000000   440.000000
mean    470.056818      42.486364  ...   47.575455  2014.318182
std     310.475077      53.039074  ...    6.925978     0.777612
min       1.000000       1.000000  ...   44.020000  2012.000000
25%     170.750000       6.000000  ...   44.430000  2014.000000
50%     456.000000      23.500000  ...   45.015000  2014.000000
75%     744.500000      52.000000  ...   47.520000  2015.000000
max    1000.000000     225.000000  ...  100.000000  2015.000000

[8 rows x 10 columns]

In [18]:
scaler1=StandardScaler().fit(x_train)
standarized_x_train=scaler1.transform(x_train)
standarized_x_test=scaler1.transform(x_test)

In [19]:
print(standarized_x_test)

[[-1.38738598 -0.73401254  0.77139525 ...  1.61035419  1.37607323
   0.89923597]
 [ 1.6749595  -0.59781816  1.12079528 ...  1.61035419 -0.47698374
   0.89923597]
 [ 1.04068729  0.37499884  0.642386   ... -0.02680875 -0.41412563
  -0.41964345]
 ...
 [ 1.52630195 -0.53944914  0.29836136 ...  1.1173658  -0.43801171
  -0.41964345]
 [ 1.14970283 -0.7145562   1.12079528 ...  0.26383366 -0.45561198
   0.89923597]
 [-1.1528374  -0.7145562   1.12079528 ... -0.63752571  0.29114232
   0.89923597]]

In [20]:
print(standarized_x_train)

[[ 1.13648882  0.23880446  1.12079528 ...  1.40800821 -0.45435482
   0.89923597]
 [-1.20899692 -0.67564352 -1.38413417 ... -1.38068732 -0.38646807
  -1.73852288]
 [ 1.61879998  0.53064956  0.31448751 ...  1.1173658  -0.44304036
  -0.41964345]
 ...
 [-0.8257908   0.91977637 -0.88959874 ... -1.12315607 -0.01309091
  -0.41964345]
 [-0.79936279 -0.44216744  0.69076447 ... -0.45357482 -0.09354929
   0.89923597]
 [ 1.76745752 -0.44216744  0.97565988 ...  1.25348946 -0.48075522
   0.89923597]]

In [21]:
normalizer1=Normalizer().fit(x_train)
normalized_x_train=normalizer1.transform(x_train)
normalized_x_test=normalizer1.transform(x_test)

In [22]:
print(normalized_x_train)

[[0.30120481 0.01955387 0.2132124  ... 0.30684535 0.01663583 0.75771248]
 [0.04487777 0.00246581 0.04980939 ... 0.02860341 0.02208381 0.99273568]
 [0.34063051 0.02409952 0.14999253 ... 0.26509471 0.01594525 0.72442434]
 ...
 [0.10015184 0.0420928  0.09337829 ... 0.06192964 0.02310266 0.9744242 ]
 [0.10030244 0.00793089 0.2271967  ... 0.14462213 0.0219779  0.94004384]
 [0.34910515 0.00598265 0.19003708 ... 0.27238648 0.01549506 0.70911984]]

In [23]:
print(normalized_x_test)

[[1.55482341e-02 8.40445089e-04 2.10951717e-01 ... 3.66013836e-01
  2.47090856e-02 8.46748427e-01]
 [3.43443399e-01 3.20642178e-03 2.02004572e-01 ... 3.10310374e-01
  1.56972159e-02 7.17882209e-01]
 [2.97859622e-01 2.27638830e-02 1.84426035e-01 ... 1.64362952e-01
  1.71925191e-02 7.77058650e-01]
 ...
 [3.20529564e-01 4.18536972e-03 1.44395255e-01 ... 2.57051457e-01
  1.54754045e-02 7.02444551e-01]
 [3.10907176e-01 1.15866029e-03 2.18986794e-01 ... 1.95041148e-01
  1.70825148e-02 7.78233491e-01]
 [5.09554323e-02 1.41542867e-03 2.67516019e-01 ... 1.22670485e-01
  2.36706855e-02 9.50696260e-01]]

In [24]:
# Practical 2.2----------------
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
bstfeatures=SelectKBest(score_func=chi2, k=10)
fit=bstfeatures.fit(x,y)
dfscr=pd.DataFrame(fit.scores_)
dfcol=pd.DataFrame(x.columns)

In [25]:
featureScores=pd.concat([dfcol,dfscr],axis=1)
featureScores.columns=['Name of Column', 'Score of Column']
print(featureScores.nlargest(10,'Score of Column'))

       Name of Column  Score of Column
0          world_rank    245586.582305
5           influence    232989.447493
4        publications    225057.530892
6           citations    194623.023346
7             patents    165004.678731
2   alumni_employment    117341.537390
3  quality_of_faculty     40707.604894
1       national_rank     28514.210009
8               score      2331.401278
9                year         0.377599

In [26]:
featureScores

       Name of Column  Score of Column
0          world_rank    245586.582305
1       national_rank     28514.210009
2   alumni_employment    117341.537390
3  quality_of_faculty     40707.604894
4        publications    225057.530892
5           influence    232989.447493
6           citations    194623.023346
7             patents    165004.678731
8               score      2331.401278
9                year         0.377599